### ISSUE TITLE
Can you please provide usage instructions?

### ISSUE THREAD

**Issue by pmarcis** [VarnithChordia/Multlingual_Punctuation_restoration#1]
Hi! I saw your EACL 2021 demonstration. Do you have an example of how to:
1) execute training and what resources are needed to train one's own model?
2) use it during inference?

Also ... I see that the code is published without a license. Could you please add a license file?

**Comment by VarnithChordia** [comment]
Hi,

Sorry for the late response. I have updated the README with instructions. Let me know if you need any help. Thanks.
